In [1]:
import numpy as np
import pandas as pd

In [2]:
nutcomp = "/content/drive/MyDrive/nutcomp.csv"
nutcomp_df = pd.read_csv(nutcomp)
nutcomp_df.head()

,NDB_No,Short_Description,Water_In_Grams,Energy_In_Kilogram_Calorie,Protein_In_Grams,Lipid_Tot_In_Grams,Ash_In_Grams,Carbohydrate_In_Grams,Fiber_TD_In_Grams,Sugar_Tot_In_Grams,...,Vit_K_In_Micrograms,FA_Sat_In_Grams,FA_Mono_In_Grams,FA_Poly_In_Grams,Cholesterol_In_Miligrams,Gram_Weight_1,Gram_Weight_Descritpion_1,Gram_Weight_2,Gram_Weight_Description_2,Refuse_Percent
0,1001,"BUTTER,WITH SALT",15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,7.0,51.368,21.021,3.043,215.0,5.00,"1 pat, (1"" sq, 1/3"" high)",14.2,1 tbsp,0.0
1,1002,"BUTTER,WHIPPED,W/ SALT",16.72,718,0.49,78.30,1.62,2.87,0.0,0.06,...,4.6,45.390,19.874,3.331,225.0,3.80,"1 pat, (1"" sq, 1/3"" high)",9.4,1 tbsp,0.0
2,1003,"BUTTER OIL,ANHYDROUS",0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,8.6,61.924,28.732,3.694,256.0,12.80,1 tbsp,205.0,1 cup,0.0
3,1004,"CHEESE,BLUE",42.41,353,21.40,28.74,5.11,2.34,0.0,0.50,...,2.4,18.669,7.778,0.800,75.0,28.35,1 oz,17.0,1 cubic inch,0.0
4,1005,"CHEESE,BRICK",41.11,371,23.24,29.68,3.18,2.79,0.0,0.51,...,2.5,18.764,8.598,0.784,94.0,132.00,"1 cup, diced",113.0,"1 cup, shredded",0.0

In [3]:
# Pencarian Duplikasi Data
print("Jumlah duplikasi: ", nutcomp_df.duplicated().sum())

Jumlah duplikasi:  0

In [4]:
# Menemukan Missing Value
nutcomp_df.isnull().sum()

NDB_No                                      0
Short_Description                           0
Water_In_Grams                              1
Energy_In_Kilogram_Calorie                  0
Protein_In_Grams                            0
Lipid_Tot_In_Grams                          0
Ash_In_Grams                              325
Carbohydrate_In_Grams                       0
Fiber_TD_In_Grams                         594
Sugar_Tot_In_Grams                       1832
Calcium_In_Miligrams                      348
Iron_In_Miligrams                         144
Magnesium_In_Miligrams                    739
Phosphorus_In_Miligrams                   579
Potassium_In_Miligrams                    426
Sodium_In_Miligrams                        83
Zinc_In_Miligrams                         706
Copper_In_Miligrams                      1257
Manganese_In_Miligrams                   2160
Selenium_In_Micrograms                   1700
Vit_C_In_Miligrams                        818
Thiamin_In_Miligrams                      634
Riboflavin_In_Miligrams                   616
Niacin_In_Miligrams                       637
Panto_Acid_In_Miligrams                  2242
Vit_B6_In_Miligrams                       905
Folate_Tot_In_Micrograms                 1261
Folic_Acid_In_Micrograms                 2039
Food_Folate_In_Micrograms                1768
Folate_DFE_In_Micrograms                 2057
Choline_Tot_In_Miligrams                 4016
Vit_B12_In_Micrograms                    1193
Vit_A_In_International_Unit               711
Vit_A_In_Retinol_Activity_Equivalents    1535
Retinol_In_Micrograms                    1806
Alpha_Carot_In_Micrograms                3258
Beta_Carot_In_Micrograms                 3162
Beta_Crypt_In_Micrograms                 3270
Lycopene_In_Micrograms                   3292
Lut_And_Zea_In_Micrograms                3315
Vit_E_In_Miligrams                       2889
Vit_D_In_Micrograms                      3262
Vit_D_In_International_Unit              3211
Vit_K_In_Micrograms                      3563
FA_Sat_In_Grams                           349
FA_Mono_In_Grams                          666
FA_Poly_In_Grams                          665
Cholesterol_In_Miligrams                  410
Gram_Weight_1                             300
Gram_Weight_Descritpion_1                 299
Gram_Weight_2                            3965
Gram_Weight_Description_2                3965
Refuse_Percent                             50
dtype: int64

In [5]:
# Mengisi nilai kosong pada kolom 'Sugar_Tot_In_Grams' & 'Fiber_TD_In_Grams' dengan 0
nutcomp_df['Sugar_Tot_In_Grams'] = nutcomp_df['Sugar_Tot_In_Grams'].fillna(0)
nutcomp_df['Fiber_TD_In_Grams'] = nutcomp_df['Fiber_TD_In_Grams'].fillna(0)

# Menampilkan DataFrame
print(nutcomp_df)

      NDB_No           Short_Description  Water_In_Grams  \
0       1001            BUTTER,WITH SALT           15.87
1       1002      BUTTER,WHIPPED,W/ SALT           16.72
2       1003        BUTTER OIL,ANHYDROUS            0.24
3       1004                 CHEESE,BLUE           42.41
4       1005                CHEESE,BRICK           41.11
...      ...                         ...             ...
8785   83110             MACKEREL,SALTED           43.00
8786   90240  SCALLOP,(BAY&SEA),CKD,STMD           70.25
8787   90480                  SYRUP,CANE           26.00
8788   90560                   SNAIL,RAW           79.20
8789   93600            TURTLE,GREEN,RAW           78.50

      Energy_In_Kilogram_Calorie  Protein_In_Grams  Lipid_Tot_In_Grams  \
0                            717              0.85               81.11
1                            718              0.49               78.30
2                            876              0.28               99.48
3                            353             21.40               28.74
4                            371             23.24               29.68
...                          ...               ...                 ...
8785                         305             18.50               25.10
8786                         111             20.54                0.84
8787                         269              0.00                0.00
8788                          90             16.10                1.40
8789                          89             19.80                0.50

      Ash_In_Grams  Carbohydrate_In_Grams  Fiber_TD_In_Grams  \
0             2.11                   0.06                0.0
1             1.62                   2.87                0.0
2             0.00                   0.00                0.0
3             5.11                   2.34                0.0
4             3.18                   2.79                0.0
...            ...                    ...                ...
8785         13.40                   0.00                0.0
8786          2.97                   5.41                0.0
8787          0.86                  73.14                0.0
8788          1.30                   2.00                0.0
8789          1.20                   0.00                0.0

      Sugar_Tot_In_Grams  ...  Vit_K_In_Micrograms  FA_Sat_In_Grams  \
0                   0.06  ...                  7.0           51.368
1                   0.06  ...                  4.6           45.390
2                   0.00  ...                  8.6           61.924
3                   0.50  ...                  2.4           18.669
4                   0.51  ...                  2.5           18.764
...                  ...  ...                  ...              ...
8785                0.00  ...                  7.8            7.148
8786                0.00  ...                  0.0            0.218
8787               73.20  ...                  0.0            0.000
8788                0.00  ...                  0.1            0.361
8789                0.00  ...                  0.1            0.127

      FA_Mono_In_Grams  FA_Poly_In_Grams  Cholesterol_In_Miligrams  \
0               21.021             3.043                     215.0
1               19.874             3.331                     225.0
2               28.732             3.694                     256.0
3                7.778             0.800                      75.0
4                8.598             0.784                      94.0
...                ...               ...                       ...
8785             8.320             6.210                      95.0
8786             0.082             0.222                      41.0
8787             0.000             0.000                       0.0
8788             0.259             0.252                      50.0
8789             0.088             0.170                      50.0

      Gram_Weight_1           Gram_Weight_Descritpion_1  Gram_Weight_2  \
0              5.00          1 pat,  (1" sq, 1/3" high)           14.2
1              3.80          1 pat,  (1" sq, 1/3" high)            9.4
2             12.80                              1 tbsp          205.0
3             28.35                                1 oz           17.0
4            132.00                        1 cup, diced          113.0
...             ...                                 ...            ...
8785          80.00  1 piece,  (5-1/2" x 1-1/2" x 1/2")           17.0
8786          85.00                                3 oz            NaN
8787          21.00                           1 serving            NaN
8788          85.00                                3 oz            NaN
8789          85.00                                3 oz            NaN

      Gram_Weight_Description_2  Refuse_Percent
0                        1 tbsp             0.0
1                        1 tbsp             0.0
2                         1 cup             0.0
3                  1 cubic inch             0.0
4               1 cup, shredded             0.0
...                         ...             ...
8785     1 cubic inch, boneless             0.0
8786                        NaN             0.0
8787                        NaN             0.0
8788                        NaN             0.0
8789                        NaN             0.0

[8790 rows x 53 columns]

In [6]:
# Menghapus kolom dengan nilai kosong
nutcomp_df_cleaned = nutcomp_df.dropna(axis=1)

# Menampilkan DataFrame yang sudah dibersihkan
nutcomp_df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   NDB_No                      8790 non-null   int64
 1   Short_Description           8790 non-null   object
 2   Energy_In_Kilogram_Calorie  8790 non-null   int64
 3   Protein_In_Grams            8790 non-null   float64
 4   Lipid_Tot_In_Grams          8790 non-null   float64
 5   Carbohydrate_In_Grams       8790 non-null   float64
 6   Fiber_TD_In_Grams           8790 non-null   float64
 7   Sugar_Tot_In_Grams          8790 non-null   float64
dtypes: float64(5), int64(2), object(1)
memory usage: 549.5+ KB

In [7]:
# Menampilkan DataFrame yang sudah dibersihkan
nutcomp_df_cleaned.head()

,NDB_No,Short_Description,Energy_In_Kilogram_Calorie,Protein_In_Grams,Lipid_Tot_In_Grams,Carbohydrate_In_Grams,Fiber_TD_In_Grams,Sugar_Tot_In_Grams
0,1001,"BUTTER,WITH SALT",717,0.85,81.11,0.06,0.0,0.06
1,1002,"BUTTER,WHIPPED,W/ SALT",718,0.49,78.30,2.87,0.0,0.06
2,1003,"BUTTER OIL,ANHYDROUS",876,0.28,99.48,0.00,0.0,0.00
3,1004,"CHEESE,BLUE",353,21.40,28.74,2.34,0.0,0.50
4,1005,"CHEESE,BRICK",371,23.24,29.68,2.79,0.0,0.51

In [8]:
# Mengubah nama kolom pada DataFrame
nutcomp_df_cleaned = nutcomp_df_cleaned.rename(columns={
    'NDB_No': 'food_id',
    'Short_Description': 'Composition',
    'Energy_In_Kilogram_Calorie': 'Calories',
    'Protein_In_Grams': 'Protein',
    'Lipid_Tot_In_Grams': 'Fat',
    'Carbohydrate_In_Grams': 'Carbohydrate',
    'Sugar_Tot_In_Grams': 'Sugar',
    'Fiber_TD_In_Grams': 'Fiber'
})

# Menampilkan DataFrame dengan nama kolom baru
nutcomp_df_cleaned.head()

,food_id,Composition,Calories,Protein,Fat,Carbohydrate,Fiber,Sugar
0,1001,"BUTTER,WITH SALT",717,0.85,81.11,0.06,0.0,0.06
1,1002,"BUTTER,WHIPPED,W/ SALT",718,0.49,78.30,2.87,0.0,0.06
2,1003,"BUTTER OIL,ANHYDROUS",876,0.28,99.48,0.00,0.0,0.00
3,1004,"CHEESE,BLUE",353,21.40,28.74,2.34,0.0,0.50
4,1005,"CHEESE,BRICK",371,23.24,29.68,2.79,0.0,0.51

In [9]:
list_allergy = "/content/drive/MyDrive/list_allergy.csv"
list_allergy_df = pd.read_csv(list_allergy)
list_allergy_df.head()

,Class,Type,Group,Food,Allergy
0,Plant origin,Nut and seed,Oil seed,Almond,Nut Allergy
1,Plant origin,Fruit,Pome fruit,Apple,Oral Allergy Syndrome
2,Plant origin,Fruit,Stone fruit,Apricot,Stone Fruit Allergy
3,Plant origin,Vegetable,Composite vegetable,Artichoke,Insulin Allergy
4,Plant origin,Vegetable,Liliaceous vegetable,Asparagus,Allium Allergy

In [10]:
#Pencarian Duplikasi Data
print("Jumlah duplikasi: ", list_allergy_df.duplicated().sum())

Jumlah duplikasi:  0

In [11]:
# Menemukan Missing Value
list_allergy_df.isnull().sum()

Class       0
Type        0
Group       0
Food        0
Allergy    22
dtype: int64

In [12]:
list_allergy_df['Allergy'].fillna('', inplace = True)

<ipython-input-12-b8b1aa9df578>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  list_allergy_df['Allergy'].fillna('', inplace = True)

In [13]:
# Menghapus kolom dengan nilai kosong
list_allergy_df_cleaned = list_allergy_df.dropna(axis=1)

# Menampilkan DataFrame yang sudah dibersihkan
list_allergy_df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Class    184 non-null    object
 1   Type     184 non-null    object
 2   Group    184 non-null    object
 3   Food     184 non-null    object
 4   Allergy  184 non-null    object
dtypes: object(5)
memory usage: 7.3+ KB

In [14]:
list_allergy_df_cleaned.isna().sum()

Class      0
Type       0
Group      0
Food       0
Allergy    0
dtype: int64

In [15]:
nutcomp_df_cleaned.to_csv("newnutcomp.csv", index=False)

In [16]:
list_allergy_df_cleaned.to_csv("newallergen.csv", index=False)